ecommerce_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres  # Docker service name, not localhost!
      user: user
      password: password
      port: 5432
      dbname: ecommerce_dw
      schema: public
      threads: 4
      keepalives_idle: 0

