{
 "title": "Business Intelligence",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Category Performance Comparison ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "ecommerce_dw",
     "rawSql": "SELECT \r\n    category,\r\n    SUM(total_revenue) as category_revenue,\r\n    SUM(total_units_sold) as units_sold,\r\n    COUNT(*) as product_count\r\nFROM product_performance\r\nGROUP BY category\r\nORDER BY category_revenue DESC;"
    }
   ]
  },
  {
   "title": "Average Customer Metrics",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecommerce_dw",
     "rawSql": "SELECT ROUND(AVG(lifetime_value)::numeric, 2) as avg_ltv\r\nFROM customer_ltv;"
    },
    {
     "dataset": "ecommerce_dw",
     "rawSql": "SELECT ROUND(AVG(lifetime_orders)::numeric, 2) as avg_orders\r\nFROM customer_ltv;"
    }
   ]
  },
  {
   "title": "Category Performance Comparison ",
   "type": "table",
   "gridPos": { "h": 17, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "ecommerce_dw",
     "rawSql": "SELECT \r\n    product_title,\r\n    category,\r\n    total_revenue,\r\n    total_units_sold,\r\n    revenue_rank,\r\n    category_rank,\r\n    pct_of_total_revenue\r\nFROM product_performance\r\nORDER BY revenue_rank\r\nLIMIT 15;"
    }
   ]
  },
  {
   "title": "Top 10 Customers by LTV",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "dataset": "ecommerce_dw",
     "rawSql": "SELECT \r\n    username,\r\n    email,\r\n    lifetime_orders,\r\n    lifetime_value,\r\n    avg_order_value,\r\n    customer_segment,\r\n    customer_tenure_days\r\nFROM customer_ltv\r\nORDER BY lifetime_value DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Top 5 Customers by Revenue",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 21 },
   "targets": [
    {
     "dataset": "ecommerce_dw",
     "rawSql": "SELECT \r\n    u.username,\r\n    u.email,\r\n    COUNT(DISTINCT f.order_id) as total_orders,\r\n    SUM(f.revenue) as total_revenue\r\nFROM fact_sales f\r\nJOIN dim_user u ON f.user_id = u.user_id\r\nGROUP BY u.user_id, u.username, u.email\r\nORDER BY total_revenue DESC\r\nLIMIT 5;"
    }
   ]
  }
 ]
}