{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Top 10 Products by Revenue",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "ecommerce_dw",
     "rawSql": "SELECT \r\n    p.product_title,\r\n    SUM(f.revenue) as total_revenue\r\nFROM fact_sales f\r\nJOIN dim_product p ON f.product_id = p.product_id\r\nGROUP BY p.product_title\r\nORDER BY total_revenue DESC\r\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Total Orders",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecommerce_dw",
     "rawSql": "SELECT \r\n    COUNT(DISTINCT order_id) as total_orders\r\nFROM fact_sales;"
    }
   ]
  },
  {
   "title": "Average Order Value",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecommerce_dw",
     "rawSql": "SELECT \r\n    ROUND(AVG(revenue)::numeric, 2) as avg_order_value\r\nFROM fact_sales;"
    }
   ]
  },
  {
   "title": "Revenue by Category",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecommerce_dw",
     "rawSql": "SELECT \r\n    c.category_name,\r\n    SUM(f.revenue) as revenue\r\nFROM fact_sales f\r\nJOIN dim_product p ON f.product_id = p.product_id\r\nJOIN dim_category c ON p.category = c.category_name\r\nGROUP BY c.category_name\r\nORDER BY revenue DESC;"
    }
   ]
  },
  {
   "title": "Revenue Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 5, "y": 14 },
   "targets": [
    {
     "dataset": "ecommerce_dw",
     "rawSql": "SELECT \r\n    DATE_TRUNC('minute', f.created_at) as time,\r\n    SUM(f.revenue) as revenue\r\nFROM fact_sales f\r\nGROUP BY DATE_TRUNC('minute', f.created_at)\r\nORDER BY time;"
    }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "ecommerce_dw",
     "rawSql": "SELECT \r\n    SUM(revenue) as total_revenue\r\nFROM fact_sales;"
    }
   ]
  },
  {
   "title": "Orders by Category",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 21 },
   "targets": [
    {
     "dataset": "ecommerce_dw",
     "rawSql": "SELECT \r\n    c.category_name,\r\n    COUNT(DISTINCT f.order_id) as order_count\r\nFROM fact_sales f\r\nJOIN dim_product p ON f.product_id = p.product_id\r\nJOIN dim_category c ON p.category = c.category_name\r\nGROUP BY c.category_name\r\nORDER BY order_count DESC;"
    }
   ]
  }
 ]
}